name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      -
        name: Create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo ".npmrc" >> .gitignore
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      -
        name: Install dependencies
        run: |
          npm install
          npm update prettier
          npm update standard
          npm audit fix
      -
        name: Check for file changes
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email github-actions@github.com
          echo "change=$(git status --porcelain)" >> $GITHUB_ENV
      -
        if: env.change
        name: Version bump
        run: |
          echo "tag=$(npm version patch)" >> $GITHUB_ENV
      -
        if: env.change
        name: Commit & push changes
        run: |
          git add -A
          git commit -a -m 'ci: update deps'
          git tag ${{ env.tag }}
          git status
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF#refs/*/} --follow-tags --force --tags
      -
        if: env.change
        name: Publish
        run: |
          npm publish
